owner: iagop03
repo: antcrew-upptime

sites:
  - name: Platform INT
    url: https://platform-int.antcrew.org/health
    expectedResponseTime: 10000

status-website:
  cname: status.antcrew.org
  name: antcrew Status
  theme: dark
  introTitle: antcrew service status
  introMessage: Real-time status for antcrew services.
  navbar:
    - title: Status
      href: /
    - title: antcrew
      href: https://antcrew.org
